eureka:
  instance:
    lease-expiration-duration-in-seconds: 9
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.40.63:8888/eureka/
spring:
  datasource:
    name: starsgroupchina
    url: jdbc:mysql://192.168.40.64:3306/hxjk_credit?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&transformedBitIsBoolean=true&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: config,slf4j,stat
      maxActive: 30
      initialSize: 2
      maxWait: 60000
      minIdle: 2
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connectionInitSqls: set names utf8mb4;

image-url: http://180.167.110.236:8088/file/

redis:
  host: 192.168.40.64
  port: 6379
  password: redis123456
  pool:
    max-idle: 8
    max-active: 8
    min-idle: 4
df:
  baseUrl: https://gateway.beeseven.com
td:
  submitUrl: https://apitest.tongdun.cn/preloan/apply/v5
  queryUrl: https://apitest.tongdun.cn/preloan/report/v9
  partnerKey: f23f418445374cf49214758180dd7bc2
qh:
  url: https://qhzx-dcs.pingan.com.cn
  msc8036: /do/dmz/query/rskdoo/v1/MSC8036
  msc8107: /do/dmz/verify/eChkPkgs/v1/MSC8107
ribbon:
  eager-load:
    enabled: true